name       : newsbeuter
version    : 2.11.1
release    : 10
source     :
    - https://newsboat.org/releases/2.11.1/newsboat-2.11.1.tar.xz : aab67dcd386a3512812e1af0fddb8e1f4dce08d2a106946fe5ad405210ed37cf
homepage   : http://www.newsbeuter.org
license    : MIT
component  : network.news
summary    : Newsboat - text terminal based RSS reader
description: |
    Open-source RSS/Atom feed reader for text terminals that runs on a variety of Unix-like operating systems. It features great configurability and a vast number of features for people who need a simple, fast reader that can completely be controlled via keyboard.
    Newsboat is a fork of Newsbeuter, an RSS/Atom feed reader for the text console. The only difference is that Newsboat is actively maintained while Newsbeuter isn't.
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - pkgconfig(stfl)
    - asciidoc
rundeps    :
    - stfl
setup      : |
    sed -i 's/\-Werror//g' Makefile
    ./config.sh
build      : |
    %make prefix=/usr
install    : |
    %make_install prefix=/usr
check      : |
    %make -j5 PROFILE=1 all test
    (cd test && TMPDIR=/dev/shm ./test --order rand)
