name       : newsbeuter
version    : '2.15'
release    : 14
source     :
    - https://newsboat.org/releases/2.15/newsboat-2.15.tar.xz : da68ce93c02dda908a471ef8994bb3c668f060eb6046d486c3f05649c6650db7
homepage   : https://newsboat.org/
license    : MIT
networking : yes
component  : network.news
summary    : Newsboat - text terminal based RSS reader
description: |
    Open-source RSS/Atom feed reader for text terminals that runs on a variety of Unix-like operating systems. It features great configurability and a vast number of features for people who need a simple, fast reader that can completely be controlled via keyboard.
    Newsboat is a fork of Newsbeuter, an RSS/Atom feed reader for the text console. The only difference is that Newsboat is actively maintained while Newsbeuter isn't.
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - pkgconfig(stfl)
    - asciidoc
    - cargo
rundeps    :
    - stfl
setup      : |
    sed -i 's/\-Werror//g' Makefile
    ./config.sh
build      : |
    %make prefix=%PREFIX%
install    : |
    %make_install prefix=%PREFIX%
check      : |
    %make -j5 PROFILE=1 all test
    (cd test && TMPDIR=/dev/shm ./test --order rand)
